const test = require("node:test");
const assert = require("node:assert/strict");
const { mkdtempSync, readFileSync, rmSync } = require("node:fs");
const { join, resolve } = require("node:path");
const { tmpdir } = require("node:os");
const { randomUUID, createHash } = require("node:crypto");

const DATA_DIR = mkdtempSync(join(tmpdir(), "narrated-evidence-integration-"));
process.env.MATCHCUTS_DATA_DIR = DATA_DIR;
const { ensureDataDirs } = require("../server/config.cjs");
ensureDataDirs();
const { LocalArtifactAdapter } = require("../server/adapters/local-artifact-adapter.cjs");
const { InMemoryArtifactRepository } = require("../server/repositories/artifact-repository.cjs");
const { ContentArtifactRepository } = require("../server/repositories/content-artifact-repository.cjs");
const { normalizeDraftBundle } = require("../server/pipelines/narrated-short/contracts.cjs");
const { createQaReport, gate } = require("../server/pipelines/narrated-short/qa/contract.cjs");
const { CONTACT_SHEET_PROFILE, EVIDENCE_PROFILE_VERSION, normalizeContactSheet } = require("../server/pipelines/narrated-short/evidence/contract.cjs");
const { generateEvidencePackage } = require("../server/pipelines/narrated-short/evidence/package-orchestrator.cjs");

test.after(() => rmSync(DATA_DIR, { recursive: true, force: true }));
const sha = (buffer) => createHash("sha256").update(buffer).digest("hex");

test("exact passing candidate produces the four bound immutable evidence artifacts", async () => {
  const artifactStore = new LocalArtifactAdapter();
  const artifactRepository = new InMemoryArtifactRepository({ persist: false });
  const contentArtifacts = new ContentArtifactRepository({ artifactStore, artifactRepository });
  const projectId = `prj_${randomUUID()}`;
  const jobId = `job_${randomUUID()}`;
  const revision = 1;
  const draft = normalizeDraftBundle(JSON.parse(readFileSync(resolve(__dirname, "..", "eval", "narrated", "dark-curiosity", "fixtures", "001_wow_signal_mystery.json"), "utf8")));
  const brief = contentArtifacts.createJson({ type: "content_brief", projectId, revision, body: draft.brief });
  const claims = contentArtifacts.createJson({ type: "claim_ledger", projectId, revision, body: draft.claimLedger });
  const script = contentArtifacts.createJson({ type: "narrative_script", projectId, revision, body: draft.script });
  const storyboard = contentArtifacts.createJson({ type: "storyboard", projectId, revision, body: draft.storyboard });
  const bundle = contentArtifacts.createJson({ type: "approval_bundle", projectId, revision, dependencyHashes: [brief.envelope.contentHash, claims.envelope.contentHash, script.envelope.contentHash, storyboard.envelope.contentHash], body: draft });
  const project = { id: projectId, input: { revision, briefArtifactId: brief.artifact.id, claimLedgerArtifactId: claims.artifact.id, scriptArtifactId: script.artifact.id, storyboardArtifactId: storyboard.artifact.id } };
  const approval = { approvalId: `capr_${"a".repeat(40)}`, projectId, projectRevision: revision, draftArtifactId: bundle.artifact.id, draftHash: bundle.envelope.contentHash, status: "approved" };
  const audioBuffer = Buffer.from("managed-audio-fixture");
  const audioHash = sha(audioBuffer);
  const audioArtifact = artifactStore.writeBuffer({ id: `art_${"d".repeat(40)}`, type: "narration_audio", ownerProjectId: projectId, ownerJobId: jobId, storageKey: `narration/${projectId}/fixture.wav`, contentType: "audio/wav", checksumSha256: audioHash, buffer: audioBuffer, status: "available" });
  artifactRepository.create(audioArtifact);
  const narration = { rights: { commercialUseAllowed: true, ownershipBasis: "self_recorded", rightsHolder: "Operator", consentReference: "consent-001", licenseReference: null } };
  const narrationManifest = contentArtifacts.createJson({ type: "narration_manifest", projectId, revision, body: { fixture: "narration" } });
  const alignment = contentArtifacts.createJson({ type: "narration_alignment", projectId, revision, body: { fixture: "alignment" } });
  const caption = contentArtifacts.createJson({ type: "caption_manifest", projectId, revision, body: { fixture: "caption" } });
  const assBuffer = Buffer.from("[Script Info]\n");
  const assHash = sha(assBuffer);
  const assArtifact = artifactStore.writeBuffer({ id: `art_${"h".repeat(40)}`, type: "caption_ass", ownerProjectId: projectId, ownerJobId: jobId, storageKey: `content/${projectId}/caption_ass/fixture.ass`, contentType: "text/x-ass", checksumSha256: assHash, buffer: assBuffer, status: "available" });
  artifactRepository.create(assArtifact);
  const normalization = contentArtifacts.createJson({ type: "audio_normalization_report", projectId, revision, body: { fixture: "normalization" } });
  const timelineArtifact = contentArtifacts.createJson({ type: "timeline_ir", projectId, revision, body: { fixture: "timeline" } });
  const outputHash = sha(Buffer.from("exact-final-output"));
  const active = { manifestArtifactId: narrationManifest.artifact.id, manifestHash: narrationManifest.envelope.contentHash, audioArtifactId: audioArtifact.id, audioHash, alignmentArtifactId: alignment.artifact.id, alignmentHash: alignment.envelope.contentHash };
  const qaBindings = { draftArtifactId: bundle.artifact.id, draftHash: bundle.envelope.contentHash, scriptHash: draft.script.contentHash, narrationManifestArtifactId: active.manifestArtifactId, narrationManifestHash: active.manifestHash, audioArtifactId: active.audioArtifactId, audioHash: active.audioHash, alignmentArtifactId: active.alignmentArtifactId, alignmentHash: active.alignmentHash, captionManifestArtifactId: caption.artifact.id, captionManifestHash: caption.envelope.contentHash, captionAssArtifactId: assArtifact.id, captionAssHash: assArtifact.checksumSha256, audioNormalizationReportArtifactId: normalization.artifact.id, audioNormalizationReportHash: normalization.envelope.contentHash, timelineArtifactId: timelineArtifact.artifact.id, timelineHash: timelineArtifact.envelope.contentHash, outputHash };
  const qaReport = createQaReport({ projectId, projectRevision: revision, renderProfile: "final", bindings: qaBindings, gates: [gate("AUDIO_ALIGNMENT_EXACT", "audio", true), gate("CAPTION_ALIGNMENT_EXACT", "caption", true), gate("CONTENT_APPROVAL_EXACT", "content", true), gate("VIDEO_FILE_READABLE", "rendered_video", true), gate("RIGHTS_NARRATION_COMMERCIAL", "rights", true), gate("TIMELINE_HASH_VALID", "timeline", true)] });
  const qaArtifact = contentArtifacts.createJson({ type: "qa_report", projectId, revision, body: qaReport });
  const contactBuffer = Buffer.concat([Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]), Buffer.from("fixture")]);
  const contactHash = sha(contactBuffer);
  const contactId = `art_${"k".repeat(40)}`;
  const contactRecord = artifactStore.writeBuffer({ id: contactId, type: "contact_sheet", ownerProjectId: projectId, ownerJobId: jobId, storageKey: `content/${projectId}/contact_sheet/fixture.png`, contentType: "image/png", checksumSha256: contactHash, buffer: contactBuffer, status: "available" });
  artifactRepository.create(contactRecord);
  const generateContactSheet = async ({ bindings }) => ({ artifact: contactRecord, descriptor: normalizeContactSheet({ schemaVersion: 1, profile: CONTACT_SHEET_PROFILE, profileVersion: EVIDENCE_PROFILE_VERSION, bindings, artifactId: contactId, checksumSha256: contactHash, width: 1080, height: 1280, frameCount: 6, timestampsSeconds: [1, 3, 5, 7, 9, 11], rendererVersion: "ffmpeg_contact_sheet_v1" }) });
  const result = await generateEvidencePackage({ project, approval, draftEnvelope: { ...bundle.envelope, artifactId: bundle.artifact.id }, draft, active, narration, captionManifestArtifact: caption, captionAssArtifact: assArtifact, normalizationArtifact: normalization, timelineArtifact, qaArtifact, qaReport, qaAnalysis: { durationSeconds: 12, width: 1080, height: 1920, fps: 30, videoCodec: "h264", audioCodec: "aac", pixelFormat: "yuv420p", audioSampleRate: 48000 }, outputHash, outputPath: "/managed/staging/final.mp4", timeline: { totalFrames: 360, fps: 30 }, artifactStore, artifactRepository, contentArtifacts, jobId, fontId: "Arial" }, { generateContactSheet });
  assert.equal(result.status, "complete");
  assert.equal(result.metadata.publishable, false);
  assert.equal(result.metadata.publishApprovalRequired, true);
  assert.equal(result.rights.bindings.outputHash, outputHash);
  assert.equal(result.provenance.dependencies.find((item) => item.role === "final_output").hash, outputHash);
  assert.deepEqual(artifactRepository.listByOwner({ projectId }).filter((item) => ["contact_sheet", "rights_manifest", "provenance_report", "export_metadata"].includes(item.type)).map((item) => item.type).sort(), ["contact_sheet", "export_metadata", "provenance_report", "rights_manifest"]);
});
