const { createHash } = require("node:crypto");
const { mkdirSync, renameSync, writeFileSync } = require("node:fs");
const { join, resolve } = require("node:path");
const { AppError, SAFE_MESSAGES } = require("../../../errors.cjs");
const { sanitizeText } = require("../../../repositories/ids.cjs");
const { contentHash } = require("../contracts.cjs");

const PROFILE = "dark_curiosity_operator_proof_v1";
const VERSION = "1.0.0";
function fail(field) { throw new AppError("OPERATOR_PROOF_INVALID", SAFE_MESSAGES.PILOT_REPORT_INVALID, 409, { field }); }
function exact(value, keys, field) { if (!value || typeof value !== "object" || Array.isArray(value)) fail(field); const allowed = new Set(keys); for (const key of Object.keys(value)) if (!allowed.has(key)) fail(`${field}.${key}`); }
function hash(value, field, optional = false) { if (optional && !value) return null; const safe = sanitizeText(value, 80).toLowerCase(); if (!/^[a-f0-9]{64}$/.test(safe)) fail(field); return safe; }
function id(value, pattern, field, optional = false) { if (optional && !value) return null; const safe = sanitizeText(value, 110); if (!pattern.test(safe)) fail(field); return safe; }
function ref(value, field) { if (!value) return null; exact(value, ["artifactId", "hash"], field); return { artifactId: id(value.artifactId, /^(art|exp)_[A-Za-z0-9-]{8,80}$/, `${field}.artifactId`), hash: hash(value.hash, `${field}.hash`) }; }
function output(value, field) { if (!value) return null; exact(value, ["artifactId", "hash"], field); return ref(value, field); }
function boundedStrings(value, field, max = 16) { if (!Array.isArray(value) || value.length > max) fail(field); const result = value.map((item) => sanitizeText(item, 120)); if (result.some((item) => !item) || new Set(result).size !== result.length) fail(field); return result; }
function noLeak(value) { const text = JSON.stringify(value); if (/\/Users\/|\/private\/|storageKey|releaseToken|tokenHash|transcript|stdout|stderr|secret/i.test(text)) fail("leak"); }

function normalizeOperatorProof(input = {}) {
  exact(input, ["schemaVersion", "profile", "profileVersion", "status", "fixture", "operatorIdentityHash", "environment", "preflight", "rehearsal", "project", "contentApprovalId", "artifacts", "outputs", "qa", "evidence", "pilotReport", "release", "technicalFinal", "publishable", "publishApprovalRequired", "completedStages", "durationMs", "blockers", "nextAction", "technicalHash"], "operatorProof");
  if (Number(input.schemaVersion) !== 1 || input.profile !== PROFILE || input.profileVersion !== VERSION) fail("profile");
  const status = sanitizeText(input.status, 24); if (!["complete", "blocked", "failed", "report_only"].includes(status)) fail("status");
  exact(input.fixture, ["fixtureId", "hash"], "fixture"); const fixture = { fixtureId: id(input.fixture.fixtureId, /^[A-Za-z0-9._-]{1,100}$/, "fixture.fixtureId"), hash: hash(input.fixture.hash, "fixture.hash") };
  exact(input.environment, ["status", "pythonAvailable", "pythonVersion", "packageReady", "modelReady", "helperAvailable", "cacheWritable", "freeDiskMb", "model", "device", "computeType", "alignerVersion", "nextActions"], "environment");
  const environment = { status: sanitizeText(input.environment.status, 30), pythonAvailable: input.environment.pythonAvailable === true, pythonVersion: input.environment.pythonVersion ? sanitizeText(input.environment.pythonVersion, 30) : null, packageReady: input.environment.packageReady === true, modelReady: input.environment.modelReady === true, helperAvailable: input.environment.helperAvailable === true, cacheWritable: input.environment.cacheWritable === true, freeDiskMb: input.environment.freeDiskMb == null ? null : Math.max(0, Math.floor(Number(input.environment.freeDiskMb))), model: sanitizeText(input.environment.model, 24), device: sanitizeText(input.environment.device, 24), computeType: sanitizeText(input.environment.computeType, 24), alignerVersion: sanitizeText(input.environment.alignerVersion, 100), nextActions: boundedStrings(input.environment.nextActions, "environment.nextActions") };
  exact(input.preflight, ["status", "ready", "expectedWordCount", "durationSeconds", "readingRateWpm", "audioHash"], "preflight"); const preflight = { status: sanitizeText(input.preflight.status, 30), ready: input.preflight.ready === true, expectedWordCount: Math.max(0, Math.floor(Number(input.preflight.expectedWordCount || 0))), durationSeconds: input.preflight.durationSeconds == null ? null : Number(input.preflight.durationSeconds), readingRateWpm: input.preflight.readingRateWpm == null ? null : Number(input.preflight.readingRateWpm), audioHash: hash(input.preflight.audioHash, "preflight.audioHash", true) };
  exact(input.rehearsal, ["status", "exactMatch", "expectedWordCount", "alignedWordCount", "firstMismatchIndex", "mismatchCategory"], "rehearsal"); const rehearsal = { status: sanitizeText(input.rehearsal.status, 30), exactMatch: input.rehearsal.exactMatch === true, expectedWordCount: Math.max(0, Math.floor(Number(input.rehearsal.expectedWordCount || 0))), alignedWordCount: Math.max(0, Math.floor(Number(input.rehearsal.alignedWordCount || 0))), firstMismatchIndex: input.rehearsal.firstMismatchIndex == null ? null : Math.max(0, Math.floor(Number(input.rehearsal.firstMismatchIndex))), mismatchCategory: input.rehearsal.mismatchCategory ? sanitizeText(input.rehearsal.mismatchCategory, 50) : null };
  exact(input.project, ["projectId", "revision"], "project"); const project = { projectId: id(input.project.projectId, /^prj_[A-Za-z0-9-]{8,80}$/, "project.projectId", true), revision: input.project.revision == null ? null : Math.max(1, Math.floor(Number(input.project.revision))) };
  exact(input.artifacts, ["approvedDraft", "narrationManifest", "narrationAudio", "narrationAlignment"], "artifacts"); const artifacts = { approvedDraft: ref(input.artifacts.approvedDraft, "artifacts.approvedDraft"), narrationManifest: ref(input.artifacts.narrationManifest, "artifacts.narrationManifest"), narrationAudio: ref(input.artifacts.narrationAudio, "artifacts.narrationAudio"), narrationAlignment: ref(input.artifacts.narrationAlignment, "artifacts.narrationAlignment") };
  exact(input.outputs, ["preview", "final"], "outputs"); const outputs = { preview: output(input.outputs.preview, "outputs.preview"), final: output(input.outputs.final, "outputs.final") };
  exact(input.qa, ["report", "blockingGateCount", "blockingPassedCount", "blockingFailedCount", "warningCount"], "qa"); const qa = { report: ref(input.qa.report, "qa.report"), blockingGateCount: Math.max(0, Math.floor(Number(input.qa.blockingGateCount || 0))), blockingPassedCount: Math.max(0, Math.floor(Number(input.qa.blockingPassedCount || 0))), blockingFailedCount: Math.max(0, Math.floor(Number(input.qa.blockingFailedCount || 0))), warningCount: Math.max(0, Math.floor(Number(input.qa.warningCount || 0))) };
  exact(input.evidence, ["contactSheet", "rightsManifest", "provenanceReport", "exportMetadata"], "evidence"); const evidence = { contactSheet: ref(input.evidence.contactSheet, "evidence.contactSheet"), rightsManifest: ref(input.evidence.rightsManifest, "evidence.rightsManifest"), provenanceReport: ref(input.evidence.provenanceReport, "evidence.provenanceReport"), exportMetadata: ref(input.evidence.exportMetadata, "evidence.exportMetadata") };
  exact(input.pilotReport, ["reportId", "hash"], "pilotReport"); const pilotReport = { reportId: id(input.pilotReport.reportId, /^pilot_[a-f0-9]{40}$/, "pilotReport.reportId"), hash: hash(input.pilotReport.hash, "pilotReport.hash") };
  let release = null; if (input.release) { exact(input.release, ["publishApprovalId", "approvalArtifactId", "approvalArtifactHash", "outputHash", "tokenIssued", "tokenVerified", "releaseExpiresAt", "guardedDownloadIssued", "downloadExpiresAt", "downloadVerified"], "release"); release = { publishApprovalId: id(input.release.publishApprovalId, /^papr_[a-f0-9]{40}$/, "release.publishApprovalId"), approvalArtifactId: id(input.release.approvalArtifactId, /^art_[A-Za-z0-9-]{8,80}$/, "release.approvalArtifactId"), approvalArtifactHash: hash(input.release.approvalArtifactHash, "release.approvalArtifactHash"), outputHash: hash(input.release.outputHash, "release.outputHash"), tokenIssued: input.release.tokenIssued === true, tokenVerified: input.release.tokenVerified === true, releaseExpiresAt: sanitizeText(input.release.releaseExpiresAt, 40), guardedDownloadIssued: input.release.guardedDownloadIssued === true, downloadExpiresAt: sanitizeText(input.release.downloadExpiresAt, 40), downloadVerified: input.release.downloadVerified === true }; }
  const normalized = { schemaVersion: 1, profile: PROFILE, profileVersion: VERSION, status, fixture, operatorIdentityHash: hash(input.operatorIdentityHash, "operatorIdentityHash"), environment, preflight, rehearsal, project, contentApprovalId: id(input.contentApprovalId, /^capr_[a-f0-9]{40}$/, "contentApprovalId", true), artifacts, outputs, qa, evidence, pilotReport, release, technicalFinal: input.technicalFinal === true, publishable: false, publishApprovalRequired: true, completedStages: boundedStrings(input.completedStages, "completedStages", 20), durationMs: Math.max(0, Math.min(86400000, Math.floor(Number(input.durationMs || 0)))), blockers: boundedStrings(input.blockers, "blockers"), nextAction: sanitizeText(input.nextAction, 120) };
  if (input.publishable !== false || input.publishApprovalRequired !== true) fail("publishable"); noLeak(normalized); const calculated = contentHash(normalized); if (input.technicalHash && hash(input.technicalHash, "technicalHash") !== calculated) fail("technicalHash"); return { ...normalized, technicalHash: calculated };
}

function createOperatorProof({ report, operatorId, doctor, preflight, rehearsal, bindings = {}, release = null }) {
  const blockers = []; if (doctor.status !== "ready") blockers.push(`aligner_${doctor.status}`); if (!preflight.ready) blockers.push(`narration_${preflight.status}`); if (!rehearsal.exactMatch) blockers.push(`rehearsal_${rehearsal.status}`); if (report.status !== "complete") blockers.push(report.failure ? report.failure.code.toLowerCase() : `pilot_${report.status}`); if (report.status === "complete" && !release) blockers.push("publish_approval_not_requested");
  const complete = report.status === "complete" && release && release.tokenVerified && release.guardedDownloadIssued;
  const publicRelease = release ? { publishApprovalId: release.publishApprovalId, approvalArtifactId: release.approvalArtifactId, approvalArtifactHash: release.approvalArtifactHash, outputHash: release.outputHash, tokenIssued: release.tokenIssued, tokenVerified: release.tokenVerified, releaseExpiresAt: release.releaseExpiresAt, guardedDownloadIssued: release.guardedDownloadIssued, downloadExpiresAt: release.downloadExpiresAt, downloadVerified: release.downloadVerified } : null;
  return normalizeOperatorProof({ schemaVersion: 1, profile: PROFILE, profileVersion: VERSION, status: complete ? "complete" : report.status === "report_only" ? "report_only" : report.status === "failed" ? "failed" : "blocked", fixture: report.fixture, operatorIdentityHash: createHash("sha256").update(operatorId).digest("hex"), environment: doctor, preflight: { status: preflight.status, ready: preflight.ready, expectedWordCount: preflight.expectedWordCount || 0, durationSeconds: preflight.media ? preflight.media.durationSeconds : null, readingRateWpm: preflight.readingRateWpm || null, audioHash: preflight.audioHash || null }, rehearsal: { status: rehearsal.status, exactMatch: rehearsal.exactMatch, expectedWordCount: rehearsal.expectedWordCount || 0, alignedWordCount: rehearsal.alignedWordCount || 0, firstMismatchIndex: rehearsal.firstMismatchIndex, mismatchCategory: rehearsal.mismatchCategory }, project: { projectId: report.projectId, revision: report.projectRevision }, contentApprovalId: bindings.contentApprovalId || release && release.contentApprovalId || null, artifacts: { approvedDraft: report.approvedDraft, narrationManifest: report.narrationManifest, narrationAudio: report.narrationAudio, narrationAlignment: report.narrationAlignment }, outputs: { preview: report.preview ? { artifactId: report.preview.exportArtifactId, hash: report.preview.outputHash } : null, final: report.final ? { artifactId: report.final.exportArtifactId, hash: report.final.outputHash } : null }, qa: report.qa || { report: null, blockingGateCount: 0, blockingPassedCount: 0, blockingFailedCount: 0, warningCount: 0 }, evidence: { contactSheet: report.contactSheet, rightsManifest: report.rightsManifest, provenanceReport: report.provenanceReport, exportMetadata: report.exportMetadata }, pilotReport: { reportId: report.runId, hash: report.contentHash }, release: publicRelease, technicalFinal: report.technicalFinal, publishable: false, publishApprovalRequired: true, completedStages: report.completedStages, durationMs: report.durationMs, blockers, nextAction: complete ? "operator-proof-complete" : blockers[0] || "inspect-operator-proof" });
}

function persistOperatorProof(proofInput, outputDir) { const proof = normalizeOperatorProof(proofInput); const dir = resolve(outputDir); mkdirSync(dir, { recursive: true, mode: 0o700 }); const temp = join(dir, `.operator-proof-${process.pid}.tmp`); const target = join(dir, "operator-proof-latest.json"); writeFileSync(temp, `${JSON.stringify(proof, null, 2)}\n`, { mode: 0o600 }); renameSync(temp, target); return proof; }

module.exports = { PROFILE, VERSION, createOperatorProof, normalizeOperatorProof, persistOperatorProof };
